# application.yml — главный конфигурационный файл Spring Boot.
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/bankcards}
    username: ${SPRING_DATASOURCE_USERNAME:bankcards_user}
    password: ${SPRING_DATASOURCE_PASSWORD:strong_password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  liquibase:
    change-log: ${SPRING_LIQUIBASE_CHANGELOG:classpath:db/liquibase/master.yaml}
    enabled: ${SPRING_LIQUIBASE_ENABLED:true}
    contexts: dev

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    show-sql: false

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET:"bankcards-dev-secret__change-me__Aq9!kZ7#pT4@xV2&nM8*Lr6%uS1^yD3+eG5=Qw0_9JjHhKkLlZzXx"}
    issuer: "bankcards"
    ttl-minutes: 60
