# application.yml — главный конфигурационный файл Spring Boot.
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bankcards
    username: bankcards_user
    password: strong_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  liquibase:
    change-log: classpath:db/liquibase/master.yaml
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

security:
  jwt:
    secret: "5c02ee9d2efea5e6782c1cfa49ec2d86bc92ef70d60036801879a77c922e3cc0"
    ttl-minutes: 60
