# application.yml — главный конфигурационный файл Spring Boot.
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bankcards
    username: bankcards_user
    password: strong_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  liquibase:
    change-log: classpath:db/liquibase/master.yaml
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false